In [2]:
# IRIS 
import numpy as np
import scipy.stats as st 
# -파이썬을 기반으로 하여 과학, 분석, 그리고 엔지니어링을 위한 과학적 컴퓨팅 영역의 여러 기본적인 작업을
#  위한 라이브러리
# -수치적분 루틴과 미분방정식 해석기, 방정식의 근을 구하는 알고리즘, 표준 연속/이산 확률분포와 
#  다양한 통계관련 도구 등을 제공NumPy와 Scipy를 함께 사용하면 확장 애드온을 포함한 MATLAB을 완벽하게 대체
# -기본적으로 Numpy, Matplotlib, pandas, Sympy등 과 함께 동작

with open('iris.data', 'r') as f:
    raw = f.readlines()
    
setosa_petal_len = []
versicolor_pl = []
virginica_pl = []

for line in raw[:50]:
    setosa_petal_len.append(float(line.split(',')[2]))
    
for line in raw[50:100]:
    versicolor_pl.append(float(line.split(',')[2]))
    
for line in raw[100:150]:
    virginica_pl.append(float(line.split(',')[2]))

# np.array이로 변경
setosa_petal_len = np.array(setosa_petal_len)
versicolor_pl = np.array(versicolor_pl)
virginica_pl = np.array(virginica_pl)

print(1.1 in setosa_petal_len)  
# in: 문자열을 받아서 첫 번째 문자열이 두 번째 문자열의 부분 문자열이면 True를 반환하는 불 연산자

True


In [3]:
# 사분 범위, 이상점, 평균, 정규분포 신뢰구간 함수
def my_describe(data):
    q1, med, q3 = np.quantile(data, [0.25, 0.5, 0.75])
    data_iqr = q3 - q1
    data_mean = np.mean(data)
    data_std = np.std(data)
    out_low = q1-1.5*data_iqr
    out_high = q3+1.5*data_iqr

    print('iqr: ', data_iqr)
    print('outlier: ', q1-1.5*data_iqr, '---', q3+1.5*data_iqr)
    print('mean: ', data_mean, 'median: ', med, 'std: ', data_std)
    print('95%: ', data_mean-1.96*data_std, '---', data_mean+1.96+data_std)

    b_filter = (data < out_low) | (data > out_high)
    print(data[b_filter])
    
print(my_describe(versicolor_pl))
print('*********************************************************')
print(my_describe(virginica_pl))

iqr:  0.5999999999999996
outlier:  3.1000000000000005 --- 5.499999999999999
mean:  4.26 median:  4.35 std:  0.4651881339845203
95%:  3.34823125739034 --- 6.68518813398452
[3.]
None
*********************************************************
iqr:  0.7750000000000004
outlier:  3.937499999999999 --- 7.0375000000000005
mean:  5.5520000000000005 median:  5.55 std:  0.546347874526844
95%:  4.481158165927386 --- 8.058347874526845
[]
None


In [9]:
# print(st.describe(setosa_petal_len))  # 다양한 통계량을 요약 
# st.iqr(setosa_petal_len)  # 사분 범위 - 이상치
st.ttest_ind(virginica_pl, versicolor_pl)   # 두 값의 평균검정
# st.ttest_ind(setosa_petal_len, versicolor_pl)
# st.ttest_ind(setosa_petal_len, setosa_petal_len)

Ttest_indResult(statistic=12.603779441384985, pvalue=3.1788195478061495e-22)

In [5]:
st.f_oneway(setosa_petal_len, virginica_pl, versicolor_pl)
# f_oneway : 샘플 크기가 다른 2개 이상 그룹간 일원분산분석

F_onewayResult(statistic=1179.0343277002194, pvalue=3.0519758018278374e-91)

In [6]:
# 선형개수? # 벡터, 행렬

# scalar
# -5
# -3
# -1

# vector
# [3, 4]
# [3, 4, 5, 6]

# tensor(matrix(3) +)
#[[3,4],[5,6]]

In [11]:
raw_list=[]
for line in raw[:150]:
    raw_list.append(line[:-1].split(','))
#print(raw_list)
species_labels = list(set([x[4] for x in raw_list]))
#print(species_labels)

for sample in raw_list:
    for index, value in enumerate(sample):
        if index<4:
            sample[index]=float(value)
        else:
            sample[index] = species_labels.index(value)
#rint(raw_list)
np_data = np.array(raw_list)
print(np_data)
        

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1

In [17]:
a1 = np_data[0].reshape(1,-1)  # -1: 자동 계산하여 반영해주는 방식/ 알아서 분할
print(a1)
print(np.transpose(a1))  # 세로 셀 범위를 가로 범위로, 가로 셀 범위를 세로 범위로 바꾸어 반환

[[5.1 3.5 1.4 0.2 0. ]]
[[5.1]
 [3.5]
 [1.4]
 [0.2]
 [0. ]]


In [9]:
a1 = np.array([3,4])
print(a1)

# norm
# L1: 절대값의 합.
np.abs(-3) # 절대값을 구하는 함수

L1 = np.sum(np.abs(a1))
print(L1)

# L2: 제곱값의 합
L2 = np.sum(a1**2)
print(L2)


# 원점에서부터의 거리
euclidian_dist = np.sqrt(L2)  # 제곱근을 계산
print(euclidian_dist)

# 벡터끼리의 거리
a1 = np.array([3,4])
a2 = np.array([10,20])
# np.sqrt((10-3)**2 + (20-4)**2)
dist = np.sqrt(np.sum((a2-a1)**2))
print(dist)

[3 4]
7
25
5.0
17.46424919657298


In [18]:
a1 = np.arange(1,10).reshape(3,-1)
# print(a1)
print(np.transpose(a1))
#np.linalg.eigvals(a1)
np.linalg.svd(a1)  # 특이값 분해 : 행렬을 특정한 구조로 분해하는 방식

[[1 4 7]
 [2 5 8]
 [3 6 9]]


(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))